### ISSUE TITLE
Permalinks Broken

### ISSUE THREAD

**Issue by crossreftech** [WebDevStudios/WDS-BuddyPress-Project-Framework#5]
I was able to change what I wanted on the template files but the permalinks weren't working. I tried resetting the permalinks to see if that would have an effect but no luck.

**Comment by modemlooper** [comment]
what version  of BuddyPress?

**Comment by crossreftech** [comment]
I'm only using the members area since all I need is the frontend profiles so not sure about the others. The links that are giving me trouble are the profile links on the /members page. When they are clicked it redirects to a 404 page. Instead of example.com/members/username it only redirects to example.com/username.

Since the client is looking to launch asap I have gone ahead and just added the template files in my theme folder and made modifications there. I would prefer to use this in the future so I would have the ability to change themes without hassle if needed.

Great plugin otherwise.

I'm using Buddypress Version 2.3.2.1. WordPress Version 4.3 abd BP Project Framework Version 2.3.2.1

**Comment by modemlooper** [comment]
Oh I think its loading the example.php file. There are some example codes in there for customization.

**Comment by modemlooper** [comment]
closing
